entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  dashboard:
    address: ":8080"

api:
  dashboard: true
    
providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: devarifhossain@gmail.com
      storage: /certificates/acme.json
      httpChallenge:
        entryPoint: web